
package Vista;


public class GuiBiblioteca extends javax.swing.JFrame {

    /**
     * Creates new form GuiBiblioteca
     */
    public GuiBiblioteca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        OpRegistrarSocio = new javax.swing.JMenu();
        JMRegissocio = new javax.swing.JMenuItem();
        JMRegisLibro = new javax.swing.JMenuItem();
        JMRegisPrestamos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        OpRegistrarSocio.setText("Archivo");

        JMRegissocio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMRegissocio.setText("Registrar Socio");
        JMRegissocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMRegissocioActionPerformed(evt);
            }
        });
        OpRegistrarSocio.add(JMRegissocio);

        JMRegisLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMRegisLibro.setText("Registrar Libro");
        JMRegisLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMRegisLibroActionPerformed(evt);
            }
        });
        OpRegistrarSocio.add(JMRegisLibro);

        JMRegisPrestamos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMRegisPrestamos.setText("Registrar Prestamos");
        JMRegisPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMRegisPrestamosActionPerformed(evt);
            }
        });
        OpRegistrarSocio.add(JMRegisPrestamos);

        jMenuBar1.add(OpRegistrarSocio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMRegissocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMRegissocioActionPerformed
       GuiSocio verventana = new GuiSocio();
       Escritorio.add(verventana);
       verventana.show();
    }//GEN-LAST:event_JMRegissocioActionPerformed

    private void JMRegisLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMRegisLibroActionPerformed
        // TODO add your handling code here:
        GuiLibro verventana = new GuiLibro();
       Escritorio.add(verventana);
       verventana.show();
    }//GEN-LAST:event_JMRegisLibroActionPerformed

    private void JMRegisPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMRegisPrestamosActionPerformed
        // TODO add your handling code here:
       GuiPrestamos verventana = new GuiPrestamos();
       Escritorio.add(verventana);
       verventana.show();
    }//GEN-LAST:event_JMRegisPrestamosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiBiblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem JMRegisLibro;
    private javax.swing.JMenuItem JMRegisPrestamos;
    private javax.swing.JMenuItem JMRegissocio;
    private javax.swing.JMenu OpRegistrarSocio;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
