/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.io.DataOutputStream;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author USUARIO
 */
public class GuiPrestamos extends javax.swing.JInternalFrame {

    DefaultTableModel dtm=new DefaultTableModel();
    
    int xMouse, yMouse;
    
    TableRowSorter trs;
    public GuiPrestamos() {
        initComponents();
        String[] titulo=new String[]{"Codigo Del Libro","Numero socio","Fecha Prestamo"};
        dtm.setColumnIdentifiers(titulo);
        tblDatos.setModel(dtm);
    }

//Funciones
    void agregar(){
        dtm.addRow(new Object[]{txtCodigoLI.getText(),txtNumeroSo1.getText(),txtFechaPrestamo.getText()});
    }
    
    void eliminar(){
        int fila=tblDatos.getSelectedRow();
        dtm.removeRow(fila);
    }
    
    void actualizar(){
        int fila=tblDatos.getSelectedRow();
        dtm.setValueAt(txtCodigoLI.getText(), fila, 0);
        dtm.setValueAt(txtNumeroSo1.getText(), fila, 1);
        dtm.setValueAt(txtFechaPrestamo.getText(), fila, 2);
    }
    void limpiar(){
        txtCodigoLI.setText("");
        txtNumeroSo1.setText("");
        txtFechaPrestamo.setText("");
    }
    
    
    void limpiarTabla(){
        int fila=dtm.getRowCount();
        for (int i = 0; i < fila; i++) {
            dtm.removeRow(0);
            
        }
    }
    
    void grabarArchivoTabla(){
        try {
            FileOutputStream fos=new FileOutputStream("Prestamos2.txt",true);
            DataOutputStream dos=new DataOutputStream(fos);
            for (int i = 0; i < tblDatos.getRowCount(); i++) {
                dos.writeUTF(dtm.getValueAt(i, 0).toString());
                dos.writeUTF(dtm.getValueAt(i, 1).toString());
                dos.writeUTF(dtm.getValueAt(i, 2).toString());
            }
            JOptionPane.showMessageDialog(null,"Archivo Grabado");    
        } catch (Exception e) {
        }
        limpiarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoLI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFechaPrestamo = new javax.swing.JTextField();
        btnPrestar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGrabarArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroSo1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Prestamos");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Prestamos");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Codigo del Libro");

        txtCodigoLI.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCodigoLI.setBorder(null);
        txtCodigoLI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoLIMousePressed(evt);
            }
        });
        txtCodigoLI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoLIActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Numero del Socio");

        txtFechaPrestamo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtFechaPrestamo.setBorder(null);
        txtFechaPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFechaPrestamoMousePressed(evt);
            }
        });
        txtFechaPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaPrestamoActionPerformed(evt);
            }
        });

        btnPrestar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnPrestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/account-multiple.png"))); // NOI18N
        btnPrestar.setText("Prestar");
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/icons8-eliminar-48.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGrabarArchivo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnGrabarArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/icons8-libro-abierto-30.png"))); // NOI18N
        btnGrabarArchivo.setText("Grabar Archivo");
        btnGrabarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarArchivoActionPerformed(evt);
            }
        });

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Fecha del prestamo");

        txtNumeroSo1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNumeroSo1.setBorder(null);
        txtNumeroSo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNumeroSo1MousePressed(evt);
            }
        });
        txtNumeroSo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroSo1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/icons8-editar-archivo-48.png"))); // NOI18N
        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaPrestamo)
                            .addComponent(txtNumeroSo1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(txtCodigoLI))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPrestar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGrabarArchivo)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoLI, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNumeroSo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrestar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGrabarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoLIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoLIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoLIActionPerformed

    private void txtCodigoLIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoLIMousePressed

    }//GEN-LAST:event_txtCodigoLIMousePressed

    private void txtFechaPrestamoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaPrestamoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaPrestamoMousePressed

    private void txtFechaPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaPrestamoActionPerformed

    private void txtNumeroSo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroSo1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroSo1MousePressed

    private void txtNumeroSo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroSo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroSo1ActionPerformed

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        // TODO add your handling code here:
       agregar();
       limpiar();
        txtCodigoLI.requestFocus();
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
       eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     actualizar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGrabarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarArchivoActionPerformed
        // TODO add your handling code here:
       grabarArchivoTabla();
    }//GEN-LAST:event_btnGrabarArchivoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabarArchivo;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtCodigoLI;
    private javax.swing.JTextField txtFechaPrestamo;
    private javax.swing.JTextField txtNumeroSo1;
    // End of variables declaration//GEN-END:variables
}
